"""
Django settings for DjangoUserService project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

import pymysql
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = "") -> list[str]:
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


ENVIRONMENT = os.getenv("ENV", "dev").strip().lower()
SUPPORTED_ENVIRONMENTS = {"dev", "development", "test", "testing", "prod", "production"}
if ENVIRONMENT not in SUPPORTED_ENVIRONMENTS:
    supported = ", ".join(sorted(SUPPORTED_ENVIRONMENTS))
    raise ImproperlyConfigured(f"Unsupported ENV {ENVIRONMENT!r}; expected one of: {supported}")
IS_PRODUCTION = ENVIRONMENT in {"prod", "production"}
IS_TEST = ENVIRONMENT in {"test", "testing"}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('JWT_SECRET_KEY') or os.getenv('SECRET_KEY')
if not SECRET_KEY and not IS_PRODUCTION:
    SECRET_KEY = "dev-only-change-me-doki-user-service"
if IS_PRODUCTION and (not SECRET_KEY or len(SECRET_KEY) < 32 or "change-me" in SECRET_KEY.lower()):
    raise ImproperlyConfigured("Production JWT secret must be a non-placeholder value of at least 32 characters")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", not IS_PRODUCTION)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured("DJANGO_DEBUG must be false in production")

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1" if not IS_PRODUCTION else "")
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("DJANGO_ALLOWED_HOSTS is required in production")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_yasg',

    
    'apps.user.apps.UserConfig',
    'apps.file',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoUserService.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoUserService.wsgi.application'

# settings.py
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 数据库后端短名称 → Django 完整路径映射
DB_ENGINE_MAP = {
    'mysql': 'django.db.backends.mysql',
    'postgresql': 'django.db.backends.postgresql',
    'sqlite3': 'django.db.backends.sqlite3',
    'oracle': 'django.db.backends.oracle',
}

raw_engine = os.getenv('DB_ENGINE', 'mysql')
# 支持短名称 (mysql)、已有完整路径 (django.db.backends.xxx) 或其他自定义
if raw_engine in DB_ENGINE_MAP:
    db_engine = DB_ENGINE_MAP[raw_engine]
elif raw_engine.startswith('django.db.backends.'):
    db_engine = raw_engine
else:
    db_engine = f'django.db.backends.{raw_engine}'

DATABASES = {
    'default': {
        'ENGINE': db_engine,
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# 仅 MySQL 才设置 utf8mb4 选项
if db_engine == 'django.db.backends.mysql':
    DATABASES['default']['OPTIONS'] = {
        'charset': 'utf8mb4',
        'use_unicode': True,
        'init_command': 'SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci',
    }

# 使用 MySQL 时，用 PyMySQL 模拟 MySQLdb
if db_engine == 'django.db.backends.mysql':
    pymysql.install_as_MySQLdb()

# Celery 配置
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
# 统一时区设置
CELERY_TIMEZONE = 'Asia/Shanghai'
# 启用UTC
CELERY_ENABLE_UTC = False
# 设置任务队列
CELERY_TASK_QUEUES = {
    'default': {
        'exchange': 'default',
        'routing_key': 'default',
    },
    'email': {
        'exchange': 'email',
        'routing_key': 'email.tasks',
    }
}
# 设置任务路由
CELERY_TASK_ROUTES = {
}
# 任务执行超时时间（秒）
CELERY_TASK_TIME_LIMIT = 10
# 任务软超时时间（秒）
CELERY_TASK_SOFT_TIME_LIMIT = 8
# 任务结果过期时间（秒）
CELERY_RESULT_EXPIRES = 3600

# redis缓存设置
REDIS_CACHE_URL = os.getenv('REDIS_CACHE_URL')
if IS_PRODUCTION and not REDIS_CACHE_URL:
    raise ImproperlyConfigured("REDIS_CACHE_URL is required for production token revocation")
if IS_TEST:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
elif REDIS_CACHE_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_CACHE_URL,
        }
    }
else:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


# 语言编码
LANGUAGE_CODE = 'zh-hans'

# 统一使用上海时区
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True
# 禁用时区支持，与Celery配置保持一致
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Browser origins are explicit. Wildcard + credentials is never allowed.
CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", False)
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173" if not IS_PRODUCTION else "",
)
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")
if IS_PRODUCTION and (CORS_ALLOW_ALL_ORIGINS or not CORS_ALLOWED_ORIGINS):
    raise ImproperlyConfigured("Production requires an explicit CORS_ALLOWED_ORIGINS allowlist")

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if IS_PRODUCTION else None

# 覆盖默认的用户模型
AUTH_USER_MODEL = 'user.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.user.authentications.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 权限类
    ],
    # 3. 全局分页
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 每页默认显示数量
    'PAGE_SIZE': 10
}

APPEND_SLASH = True
